title: "Marcin Jałbrzykowski - Beyond code & evil"
description: "My personal thoughts about software engineering"
baseurl: ""
url: "http://jalbrzykowski.net"

gems: [ "jekyll-paginate", "jekyll-sass-converter" ]
markdown: kramdown

paginate: 5
paginate_path: "/page/:num/"

sass:
  style: compressed
 